### ISSUE TITLE
Crashing when tab menu is opened on Hypixel

### ISSUE THREAD

**Issue by Durjam** [vladmarica/better-ping-display-fabric#1]

**Comment by vladmarica** [comment]
Hello, I am unable to replicate this crash. Could you give me the following info?

- What Minecraft version are you running, 1.15 or 1.16?
- What were you doing on Hypixel when it crashed? Specifically, which minigame?

Thanks!

**Comment by vladmarica** [comment]
I found the bug and fixed it in cc9427d
