### ISSUE TITLE
Publish 1.19.2 tagged release to CurseForge

### ISSUE THREAD

**Issue by vladmarica** [vladmarica/better-ping-display-fabric#17]
Users are unable to find the mod when searching for 1.19.2 mods on CurseForge because this mod has no released tagged as such.

**Comment by ghost** [comment]
Same for Modrinth. This also makes impossible to automatic install the mod via modpack tools such as Packwiz.

**Comment by vladmarica** [comment]
CurseForge: https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/4018586
Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.19.2-1.1.1
