### ISSUE TITLE
Add 1.19.3 support pls

### ISSUE THREAD

**Issue by voidrinix** [vladmarica/better-ping-display-fabric#21]

**Comment by TechPro424** [comment]
Please add 1.19.3 support

**Comment by DenaryDev** [comment]
Check this [Pull Request](https://github.com/vladmarica/better-ping-display-fabric/pull/20)
You can download mod jar from the comments to it

**Comment by vladmarica** [comment]
Done.

CurseForge: https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/4301047
Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.19.3-1.1.1
