### ISSUE TITLE
Please update the mod to 1.19.4

### ISSUE THREAD

**Issue by TechPro424** [vladmarica/better-ping-display-fabric#23]
Please update the mod to 1.19.4

**Comment by Razuuu** [comment]
https://github.com/Razuuu/better-ping-display-fabric/releases
(Also added ping command)

**Comment by TechPro424** [comment]
Thanks
One more request
Please publish the version to modrinth releases

Edit: nvm just realized that it was a fork

**Comment by TechPro424** [comment]
@vladmarica any update on this? (not pressuring you, take your time)

**Comment by Aces-and-Jacks** [comment]
updated, this can be closed now
