### ISSUE TITLE
Add 1.20 support

### ISSUE THREAD

**Issue by vladmarica** [vladmarica/better-ping-display-fabric#25]
Tracking bug for Minecraft 1.20 support

**Comment by vladmarica** [comment]
Preliminary 1.20 prerelease port was added in 0f98105d1a5175fde4d98852040bd460257cf1d5 and was released as a beta.

Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.20-pre-1.1.1
CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/4552752

**Comment by vladmarica** [comment]
1.20.1 support was added in [dc0edb8](https://github.com/vladmarica/better-ping-display-fabric/commit/dc0edb8d502b79d1fbd8b42aeb0980897aba7267) and released:

Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.20.1-1.1.1
CurseForge: https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/4592448

**Comment by pointydev** [comment]
Would be great if 1.20.2 support was added, as this is one of the mods blocking my upgrade.
