### ISSUE TITLE
Sodium crash

### ISSUE THREAD

**Issue by Moksh9900** [vladmarica/better-ping-display-fabric#27]
Sodium is crashing when joining a server 
This is link of crash 
https://bytebin.lucko.me/dN8mDJmkjE

Pls fix 
Thank you

**Comment by krafg** [comment]
This mod works well with sodium

**Comment by vladmarica** [comment]
That link does not work. Also, there haven't been other reports of Sodium not working with this mod. Please re-open this issue if it occurs again.
