### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by Arthurmeade12** [vladmarica/better-ping-display-fabric#34]
Sorry that I can't give more information on what is causing the crash.

Log: [https://mclo.gs/tZKUHuh](https://mclo.gs/tZKUHuh)

Thanks for any help.

**Comment by joshuayuen99** [comment]
Looks like you're also using the PingList mod, which appears to be incompatible with this mod. I'd remove one or the other and see if that fixes it.

**Comment by Arthurmeade12** [comment]
How silly of me. Yes, thank you. Removing PingList solved this issue.
