### ISSUE TITLE
1.20.4 support

### ISSUE THREAD

**Issue by TechPro424** [vladmarica/better-ping-display-fabric#35]
Seems to be fixed by #33

**Comment by vladmarica** [comment]
Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.20.4-1.1.1
CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/5041642

Sorry for the delay. Future version updates will be much more timely.
