### ISSUE TITLE
Add compatibility to 1.20.5

### ISSUE THREAD

**Issue by krafg** [vladmarica/better-ping-display-fabric#38]
Hi. today was released MC 1.20.5, so we wait for add compatibility. Modifying fabric.mod.json it works.

Regards.

**Comment by vladmarica** [comment]
Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.20.5-1.1.1
CurseForge: https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/5325435
