### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by KozukiYOMA** [vladmarica/better-ping-display-fabric#40]
I added the mod but the ping display is not changing.
It did change at first.

[crash-2024-05-31_04.59.29-client.txt](https://github.com/vladmarica/better-ping-display-fabric/files/15505191/crash-2024-05-31_04.59.29-client.txt)

[latest.log](https://github.com/vladmarica/better-ping-display-fabric/files/15505196/latest.log)

**Comment by KozukiYOMA** [comment]
I am not going to post a screenshot because it will just be a vanilla display, not a number.

It would be easier to know if it's a bug or not if you could toggle the mod on and off...

**Comment by vladmarica** [comment]
It's likely some conflict with one of your mods. Can you try removing Essential and seeing if that fixes it?

**Comment by KozukiYOMA** [comment]
I think it's different because there was a time when I was able to do it while putting Essential...

**Comment by KozukiYOMA** [comment]
I deleted Essential and started it, but it did not resolve the issue.

**Comment by KozukiYOMA** [comment]
I tried removing the mods that change the display of the player list, but it did not solve the problem.

**Comment by KozukiYOMA** [comment]
It seems that it was not reflected by a feature of Noxesium (maybe). Changing the setting fixed the problem. (In addition, the problem of the Essentials icon not being displayed has also been fixed.)
