### ISSUE TITLE
1.21.3 not working

### ISSUE THREAD

**Issue by Stoupy51** [vladmarica/better-ping-display-fabric#45]
The mod does not work with 1.21.3:

![image](https://github.com/user-attachments/assets/b1120fad-bf26-4e77-80ee-518d80865502)

**Comment by vladmarica** [comment]
Added 1.21.3 support

- Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.21.3-1.1.1
- CurseForge: https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/5932632
