### ISSUE TITLE
Support for 1.21.4

### ISSUE THREAD

**Issue by dennisthegamer** [vladmarica/better-ping-display-fabric#46]
version 1.21.3 is not compatible with 1.21.4 
![image](https://github.com/user-attachments/assets/9cdf5eab-b3c7-4cc7-9c66-b66f5647d4f2)

**Comment by vladmarica** [comment]
CurseForge: https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/6038858
Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.21.4-1.1.1
