### ISSUE TITLE
add 1.18.2 support 

### ISSUE THREAD

**Issue by thiagogebrimm** [vladmarica/better-ping-display-fabric#9]
The plugin doesn't work in 1.18.2

**Comment by rostikmak** [comment]
Dear author, WE NEED 1.18.2 PLEASE HEEEELP.
Thanks a lot!

**Comment by EGOIST1372** [comment]
@vladmarica any news on the state of this issue?
thanks in advance

**Comment by vladmarica** [comment]
Done: https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/3790832
